M48
; DRILL file {KiCad 9.0.4} date 2025-11-21T01:19:34-0600
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-11-21T01:19:34-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.4
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X170.472Y-57.33
X175.172Y-57.33
T2
X152.95Y-55.8
X152.95Y-95.25
X225.0Y-55.8
X225.0Y-95.25
M30
