M48
; DRILL file {KiCad 9.0.4} date 2025-11-25T13:51:55-0600
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-11-25T13:51:55-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.4
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X155.8Y-54.78
X160.5Y-54.78
T2
X134.5Y-53.5
X134.5Y-95.75
X225.0Y-53.5
X225.0Y-95.75
M30
